.travis.yml
adhocracy-plus/config/settings/test.py

For once because we use it on our production system and also because it is usually more strict.

ci: Use postgresql instead of sqlite

---

adhocracy-plus/config/settings/base.py

We should really stop to set instance specific settings in the project.
Lets use the salt pillars instead.

settings: Replace CONTACT_MAIL with a placeholder

---

apps/users/forms.py
apps/users/models.py

The current session language (which again was based on the browser language
or manual selection) was not saved any more after !47.
While on it, make sure it is also set for social logins.

apps/users: Fix language selection on registration

---

requirements/base.txt

This version is a long term release, so lets pin it until we have
good reasons to update again (lik the django 2.2 update before).

deps: Update wagtail to 2.7

---

package.json
webpack.common.js

Supporting outdated or rarely used browsers makes everyone else
slower. Let's reduce the list to a reasonable number. We don't test
the other browser anyway, they might be broken without us knowing.

webpack: Remove commonjs plugin and reduce supported browsers

---

package.json
webpack.common.js

Removing the commonjs produced errors that the linter didn't catch:
mixing es5 and es6 classes is actually not supported by browsers,
but we do it in our code. As long as we don't clean that up, let's
stick to the commonjs translation which works around this.

webpack: Readd commonjs translation

---

Makefile

Whe need GNU sed for the `make po` command, but MacOS uses the BSD
version by default. If then GNU sed is installed additionally, it is
named gsed.

Makefile: Use gsed if it exists (MacOS)

---

adhocracy-plus/config/settings/base.py

Reverts liqd/adhocracy-plus#396
Well, this broke the migrations where pgettext is used (in a4/comments/models/meta)

Revert "settings: set default user language and site-wide default to same lan…"

---

apps/account/templates/a4_candy_account/profile.html

We hide the language field so the platform is german only. But apparently it
is mandatory for the backend, so it would not accept post actions that don't
include the language field.
fixes https://github.com/liqd/adhocracy-plus/issues/425

templates/profile: Add hidden language field

---

Makefile
apps/projects/emails.py
apps/projects/templates/a4_candy_projects/emails/delete_project.de.email
apps/projects/templates/a4_candy_projects/emails/delete_project.en.email
apps/users/emails.py

From the relevant commit:
```
This makes most mails use the organisation settings/logo, especially notifications.
Also corrects the project delete email to return a proper organisation object
on `get_organisation()` to be in line with other mails.
```
Fixes https://github.com/liqd/adhocracy-plus/issues/465

emails: Always add organisation to context in EmailAplus

---

apps/newsletters/emails.py
apps/projects/emails.py
apps/users/emails.py

All mail classes inheriting from EmailAplus need to attach the organisation
logo - so move the code there. Fixes certain emails lacking any logo.

emails: Move organisation logo attachment to EmailAplus

---

apps/users/emails.py

This should make sure we send invitations in german. In the long term we probably want to have the possibility to have a organisation language.

apps/users/emails: Take default user language into account

---

apps/users/forms.py

Add proper hints to login and signup forms so browsers do not use the wrong
forms for password saving. This is especially visibile when we have extra
fields, like in the IG-BCE form.
Fixes https://github.com/liqd/adhocracy-plus/issues/449

users/forms: Add autocomplete hints

---

package.json

Apparently a newer version is either installed as dependecy or it
is bundled in - either way, this package version got deprecated and
won't install any more and things appear to work just fine without it.

deps: Remove deprecated popper.js

---

adhocracy-plus/templates/email_base.html

Otherwise certain clients like the MacOS mail client chooses to
display the attached logo anyways.
Fixes https://github.com/liqd/adhocracy-plus/issues/262

templates/email_base: Add HTML tag for unused logo

---

adhocracy-plus/assets/js/app.js
adhocracy-plus/assets/js/popover.js
apps/embed/assets/embed.js
apps/maps/assets/map-address.js
apps/maps/assets/map_choose_polygon_with_preset.js
package.json
requirements/base.txt

When using multple webpack endpoints we do not get a global jQuery
object but instead one for each endpoint. These do not see each others
signals, thus do not fire.
Use standard js events instead - they don't suffer from that problem and
we should get rid of jQuery anyway over time.
Also use the chance to clean up the init syntax.
Depends on https://github.com/liqd/adhocracy4/pull/519

assets: Replace jQuery 'a4.embed.ready' listeners with vanilla js

---

package.json

Reverts liqd/adhocracy-plus#537
above update breaks header dropdown on mobile, will look at proper fix after I have finished work on header, for now it needs to work for mobile testing

Revert "Update dependency jquery to v3.5.0"

---

apps/users/emails.py

fixes #554
Apparently MacOS client (and maybe others) display all images that are attached, even if they are not used. One can suppress this behaviour with display=False, but the image is still sent in the attachments.
That is why I thought maybe its better to completely remove the a+ logo from the attachment if the organisation logo is used. What do you think?

apps/users: remove standard email logo from attachment if not needed

---

package.json

Reverts liqd/adhocracy-plus#583 until jquery or bootstrap release a fix we will stay at

Revert "fix(deps): update dependency jquery to v3.5.0 [security]"

---

locale/nl_NL/LC_MESSAGES/django.po
locale/nl_NL/LC_MESSAGES/djangojs.po

fixes  #708
The problem was, that in the dutch translations  ” (left/right double quotaton marks) were used instead of ". Transifex doesnt escape them and thus the links are broken..so this is some kind of unicode thing?
We should think about a way to prevent this.

locale/nl_NL: remove wrong quotation marks that break links

---

docs/installation_prod.md

- xmlsec path must be set for djangosaml2 to work
- nodes disables key password protection, which is not helpful in
this scenario

docs: Some additions to shibboleth config

---

adhocracy-plus/templates/account/diid/saml2.html
docs/installation_prod.md

When set, the login directly forwards to the specified IDP, in
contrast to showing a full list. This does not prevent other IPDs
to send valid login tokens - thus the user needs to make sure the
own service is only registered on the desired IDP.

diid: Add a default_idp setting

---

adhocracy-plus/config/settings/dev.py

It's important to have for prod instances, but for dev it apparently
works regardless.

config/dev: Do not require xmlsec1 to be installed

---

Makefile
docs/translations.md

Appently they behave mutually exclusive anyway - if `po-fork` should be
used, `po` produces broken output.
@fuzzylogic2000 does that look sensible to you?

Makefile: Merge po-fork back into po

---

Makefile

`sed` will complain when feeded with an empty file list. Thus use a
loop to call each file individually.
Sorry, didn't test the previous solution before.

Makefile: Only call sed if file actually exists

---

docs/installation_prod.md

Otherwise a4 will not get updated, resulting in errors afterwards.
This could be fixed by turning a4 into a propper package with
versions.

docs: Add --upgrade to pip install

---

locale-source/locale/de/LC_MESSAGES/django.po
locale-source/locale/en/LC_MESSAGES/django.po
locale-source/locale/nl/LC_MESSAGES/django.po
locale-source/locale/tr/LC_MESSAGES/django.po

It's likely that someone looking to change the language doesn't know how the own language is called on another language. Always show languages in their own language in the language switcher.
Depends on and includes #940

translations: Show languages in their own language

---

adhocracy-plus/config/settings/base.py
apps/djangosaml2_overwrites/middlewares.py

djangosaml2 does not offer a way to not login the user before doing
extra validation steps. In order to force users to sign up before
being able to use the website, add a simple middleware, redirecting
them to the signup as long as their email is not verified.
Logout and wagtail pages are excepted from these rules.

adds/djangosaml2_overwrites: Add a middleware to guard saml signup

---

adhocracy-plus/assets/scss/components/_a4-comments.scss

Some small adjustments that IMO make things more pleasant to look at - but should be checked by designers/ux
Before:
After:

assets/scss/a4-comments: Styled by dev

---

apps/users/forms.py
requirements/base.txt

It now has support for "Sign in with apple"
The extra change was necessary because of https://github.com/pennersr/django-allauth/commit/b9ca281cd915a1fd8746d13538ed8c319728d4b0

deps: Update allauth to 0.43.0

---

.editorconfig
Makefile

See https://github.com/liqd/a4-meinberlin/commit/efee8c04caa850b2326eb64fb8badece45bacde9

settings: skip migrations for isort in lint-python-files

---

apps/contrib/management/commands/cleanup_unverified_users.py

Strictly speaking we should check for the email verified status here,
but if a user never logged in that pretty much implies the same.
Prints a list of deleted users, which we'll recieve as mail from
a cron job.

contrib/management: Add command to clean up unverified users

---

package.json

Reverts liqd/adhocracy-plus#920
Fix maps on safari fixes #987
workaround but just wait for next release? 
Issues:
https://github.com/Leaflet/Leaflet/issues/7331
https://github.com/Leaflet/Leaflet/issues/7255

Revert "Update dependency leaflet to v1.7.1"

---

apps/interactiveevents/assets/js/a4_candy_interactive_events/livequestion_box.jsx
apps/interactiveevents/assets/js/a4_candy_interactive_events/livequestion_form.jsx

Directly fire a update request and reset the timer, so the own question
is shown faster.

apps/interactive_events: Restart polling interval when adding question

---

apps/interactiveevents/assets/js/a4_candy_interactive_events/livequestion_statistics_box.jsx

So do actually take advatage of having the state.

interactiveevents/assets: Use state instead of props again for list

---

adhocracy-plus/config/settings/base.py
apps/embed/assets/embed.js
requirements/base.txt

The cookie test was completely broken, not sure why that should have worked in the past. And a workaround for https://code.djangoproject.com/ticket/31933

apps/embed: Some 3rd-party cookie fixes

---

adhocracy-plus/assets/js/app.js
apps/maps/assets/map-address.js
apps/maps/assets/map_choose_polygon_with_preset.js
package.json
requirements/base.txt
webpack.common.js

So I tried to find all that needed adjustment when updating A4 after the js refactoring.
I initially wanted to port over [this PR](https://github.com/liqd/a4-meinberlin/pull/3386/files) from mB, but realized that we dont need that here, as we dont have plans and the other map initialization is done in A4, right?
Also not sure about [this PR]([url](https://github.com/liqd/a4-meinberlin/pull/3387/files))? The jQuery wasnt there before and I didnt add it, because polygons seem to work fine..
And finally I am not sure, why the credits dont show for the maps.. they do locally, because they are set explicitly [here](https://github.com/liqd/adhocracy-plus/blob/23611c276e5f3a1ba1ad5b4429359e006b6014b7/adhocracy-plus/config/settings/base.py#L494), but this must be overwritten on the servers …

Ks 2021 02 update js

---

apps/organisations/sitemaps.py

This avoids 500 errors when search engines rescan projects of deleted
organisations.
Closes https://sentry.liqd.net/organizations/liqd/issues/1272/

organisations/sitemaps: Return 404 if organisation does not exist

---

apps/embed/assets/embed.js

This affects cases when people login from the login-link shown
e.g. above comments.

apps/embed/assets: Work around login popup not closing

---

Makefile

Fix the `make: command: Commant not found` warning during build. Adding the semicolon forces bash to skip some builtin optimizations and actually execute the command.

makefile: silence non-critical warning when probing for gsed

---

tests/dashboard/test_dashboard_views.py
tests/interactiveevents/test_interactiveevent_api.py

@fuzzylogic2000 I was tempted to remove [this](https://github.com/liqd/adhocracy-plus/blob/3d521b9307dd415c76cbc6fcd0ee8fdb7a7e3de3/apps/dashboard/views.py#L192-L197) from ModuleDeleteView, because I think we dont need it anymore, right? Because the dropdown with deletion option only shows if module is draft? But then I saw that these lines were only added a year ago, so not sure anymore.. do we still need that?

Ks 2021 05 more tests

---

adhocracy-plus/assets/js/app.js
adhocracy-plus/templates/a4dashboard/base_dashboard.html
webpack.common.js

fixes #1226
Although this is not the proper way, I guess we should find out why the browser thinks the information in Report Modal is not sent, even though it is..

Ks 2021 05 disable unload warning outside dashboard

---

adhocracy-plus/config/urls.py
apps/ideas/api.py
apps/ideas/serializers.py

Very basic idea api that only gives you title and description.
Idea list is available under /api/modules/<module_pk>/ideas or equivalently django.urls.reverse('ideas-list', kwargs={'module_pk':module_pk})
Idea detail is available under /api/modules/<module_pk>/ideas/<pk> or equivalently django.urls.reverse('ideas-detail', kwargs={'module_pk':module_pjk, 'pk':pk})

Ks 2021 05 add idea api

---

apps/ideas/serializers.py

This adds the user rating to idea serializer with rating_id and value. The id is needed to change a users rating, i.e. for put request. If user hasnt rated yet or is not logged in, user rating will be None.

ideas/serializers: add user rating

---

apps/budgeting/exports.py
apps/debate/exports.py
apps/documents/exports.py
apps/exports/mixins.py
apps/ideas/exports.py
apps/mapideas/exports.py
apps/polls/exports.py
apps/topicprio/exports.py
tests/exports/test_comment_exports.py
tests/exports/test_item_exports.py

still very untested, just not to forget what to do.
depends on a4, which needs to be updated.
maybe also fix #1359

apps/exports: use export mixins from a4

---

requirements/base.txt

The raven sdk has been deprecated for a while now, we should switch to the new sdk. This requires changes in our server setup as well.

jd 2021 05 upgrade to new sentry sdk

---

adhocracy-plus/config/settings/base.py

replace the hallojs richt-text editor with the newer in-built draftail editor
partly fixes #1844

wagtail: remove deprecated hallo.js richt text

---

webpack.common.js

This reverts commit 5745d5c59204d19dbbeb090c71fde5d50a5f8651.

Revert "webpack: don't export entry points as library"

---

adhocracy-plus/assets/js/init_dashboard_accordion.js
adhocracy-plus/templates/a4dashboard/base_dashboard_project.html
apps/dashboard/templatetags/a4_candy_dashboard_tags.py

project ids and module ids can overlap and therefore trigger wrong behavior. This PR stores project ids and module ids in separate lists.
closes #1951

accordion: fix overlapping project and module ideas

---

adhocracy-plus/assets/js/unload_warning.js

the unload warning currently fails when you try to enter a url for the media embed. We don't need the warning for the pop-up anyway, so just skip it

unload_warning: fix ckeditor pop-up error

---

adhocracy-plus/config/urls.py

This was interfering with https://github.com/liqd/adhocracy-plus/blob/1b9c351143aeb87f97f5b805ba2e3d21e8c8ab80/apps/account/urls.py#L8 and now the link to account settings lead to api :see_no_evil:

config/urls: remove name of api/account

---

apps/users/models.py
package.json
requirements/base.txt

depends on https://github.com/liqd/adhocracy4/pull/1175 and hash needs update after merge
with this, avatar fallbacks should show in the app

Ks 2022 08 use png avatars in app

---

adhocracy-plus/templates/a4dashboard/base_dashboard.html
adhocracy-plus/templates/a4dashboard/communication_form_base.html
adhocracy-plus/templates/a4images/image_upload_widget_simple.html
apps/contrib/widgets.py
apps/dashboard/urls.py
apps/newsletters/templates/a4_candy_newsletters/restricted_newsletter_dashboard_form.html
apps/newsletters/views.py
apps/organisations/forms.py
apps/organisations/templates/a4_candy_organisations/communication_form_social_media.html
apps/organisations/views.py

The last commit depends on https://github.com/liqd/adhocracy4/pull/1289, so that need to be merged first and the hash added.
There are still some things that need to be done:
- checkboxes for logos
- image creation with input data and for different templates
- preview/download of generated image
- tests
But maybe this is a state that could be merged and we can on from there?

[#6750] a4dashboard: add communication form

---

apps/contrib/management/commands/send_test_emails.py
apps/notifications/emails.py
apps/notifications/signals.py
apps/notifications/templates/a4_candy_notifications/emails/notify_creator_on_moderator_blocked.en.email
apps/notifications/templates/a4_candy_notifications/emails/notify_creator_on_moderator_comment_feedback.en.email

I actually could not test this, because I could neither make the send_test_emails work, nor could I trigger an email.. could someone check if this works? Maybe its just my setup? 
Both emails are sent to comment creator, one when comment is being blocked, the other when statement has been added to the comment..
Supposed to fix https://sentry.liqd.net/organizations/liqd/issues/3171/

notifications: add moderation specific emails

---

apps/projects/templates/a4_candy_projects/project_detail.html

apps/projects/templates/project_detail: add same heading to single project detail as module detail 
fixes #2252

[2252] single module project heading info added

---

adhocracy-plus/assets/scss/components/_badge.scss

this fixes the badge issue in debate module, mentioned by @lthueer here:
https://github.com/liqd/adhocracy-plus/issues/2364#issuecomment-1521960083

badge.scss: making sure bs and a4 classes are not overwritten by .badge

---

adhocracy-plus/assets/scss/components/_badge.scss

seems the `badge` class in a4 is needed because the bootstrap functionality is used.
closes #2364

styles/badge: increase specificity for badges

---

apps/userdashboard/views.py
package.json
requirements/base.txt

depends on https://github.com/liqd/adhocracy4/pull/1412

userdashboard: use new target_creator to improve filtering

---

adhocracy-plus/config/settings/base.py
adhocracy-plus/templates/account/signup.html
apps/cms/contacts/models.py
apps/contrib/templates/a4_candy_contrib/includes/form_field.html
apps/users/forms.py
changelog/2064.md
tests/users/test_signup.py

This PR fixes the error:
```
AttributeError at /accounts/signup/
'Settings' object has no attribute 'CAPTCHA_URL'
```
when no captcha is installed in the project and thus no CAPTCHA_URL in the settings.
https://github.com/liqd/adhocracy-plus/issues/2064

Fix #2064: Check catcha url exists in signup form

---

adhocracy-plus/templates/a4modules/module_detail.html
changelog/7428.md

This needs https://github.com/liqd/adhocracy4/pull/1443
@m4ra @hklarnerliqd if you want to test it, you can checkout locally the a4 pull request and link it to your local adhocracy plus, like described here: https://github.com/liqd/adhocracy4/blob/main/docs/development.md#development-setup

[7428] templates/module_detail: pass initial_slide in link back to project

---

apps/projects/models.py
tests/projects/test_insights.py

- without this fix: results tab shows optional insights (polls, live questions, ideas) for modules that are in draft state
- with this fix: only non-draft modules can trigger optional insights

[7431] fixes project insights for draft modules

---

apps/debate/models.py
tests/conftest.py
tests/contrib/test_mixins.py
tests/ideas/test_idea_api.py
tests/ideas/test_idea_models.py
tests/organisations/test_organisation_models.py
tests/projects/test_serializers.py
tests/topicprio/test_topic_models.py
tests/users/test_models.py

The intention of this refactor is to
- rename the image fixtures to adhere to Python naming conventions (camel case)
- simplify the property `last_three_creators` by filtering the query directly

refactors apps/debate and renames image fixtures

---

.eslintrc
package.json

deps: remove eslint-n 

---

changelog/_4567.md
docs/tests.md
tests/helpers.py
tests/notifications/test_creator_notifications.py

fix flaky email tests

---

adhocracy-plus/templates/a4dashboard/base_form_project.html
apps/budgeting/templates/a4_candy_budgeting/includes/proposal_form.html
apps/ideas/templates/a4_candy_ideas/idea_moderate_form.html
apps/ideas/templates/a4_candy_ideas/includes/idea_form.html
apps/interactiveevents/templates/a4_candy_interactive_events/extrafields_dashboard_form.html
apps/mapideas/templates/a4_candy_mapideas/includes/mapidea_form.html
apps/mapideas/templates/a4_candy_mapideas/mapidea_moderate_form.html
apps/newsletters/templates/a4_candy_newsletters/restricted_newsletter_dashboard_form.html
apps/offlineevents/templates/a4_candy_offlineevents/includes/offlineevent_form.html
changelog/7632.md

see https://github.com/liqd/a4-meinberlin/commit/e1aecbae8fb529ae1bb8b58e1d761827a8a15485
fixes #2571
**Tasks**

forms shouldn't use browser validation but our own error messages.

---

apps/account/views.py

Testing: go to http://127.0.0.1:8004/account/profile/ and change the language, both alert and rest of the page should be in the new language
**Tasks**

fix mixed language on profile page when changing prefered user language there

---

adhocracy-plus/config/settings/base.py
apps/topicprio/templates/a4_candy_topicprio/includes/topic_form.html

fixes #2570, fixes #2579
**Tasks**

fix ckeditor5 uploads as initiator and disable form validation to allow saving ckeditor5 form for topicprio

---

Makefile
apps/projects/models.py
locale-source/locale/de/LC_MESSAGES/django.po
locale-source/locale/de/LC_MESSAGES/djangojs.po
locale-source/locale/en/LC_MESSAGES/django.po
locale-source/locale/en/LC_MESSAGES/djangojs.po
locale-source/locale/hu/LC_MESSAGES/django.po
locale-source/locale/hu/LC_MESSAGES/djangojs.po
locale-source/locale/ky/LC_MESSAGES/django.po
locale-source/locale/ky/LC_MESSAGES/djangojs.po
locale-source/locale/nl/LC_MESSAGES/django.po
locale-source/locale/nl/LC_MESSAGES/djangojs.po
locale-source/locale/ru/LC_MESSAGES/django.po
locale-source/locale/ru/LC_MESSAGES/djangojs.po
locale-source/locale/tr/LC_MESSAGES/django.po
locale-source/locale/tr/LC_MESSAGES/djangojs.po

fixes #2521
also updates and removes obsolete translations 
**Tasks**

fix wording for the insights

---

adhocracy-plus/assets/scss/components/_userdashboard.scss
changelog/1842.md

mobile screens
fixes #1842
can be tested with small screen sizes here: http://127.0.0.1:8004/userdashboard/overview/
**Tasks**

userdashboard: fix padding and dropdown icon on userdashboard nav for

---

adhocracy-plus/assets/scss/components/_blocks.scss
apps/cms/use_cases/templates/a4_candy_cms_use_cases/blocks/use_cases_block.html
changelog/1760.md

- fix non-matching paddings and margins for background cta block
- fix broken styling on mobile for usecase block
fixes #1760
to test this you need to create the different blocks in wagtail (e.g.  first add usecase pages (index and page)) and  then add usecase block and background cta block to the homepage
before:
after:
before:
after:
**Tasks**

apps/cms: fix multiple block styling issues

---

adhocracy-plus/assets/scss/components/_dropdown.scss
adhocracy-plus/assets/scss/components/_tabs.scss
apps/projects/templates/a4_candy_projects/project_detail.html

Fixes #2506 
Adjusted tablist z-index to align with main section cards. 
Fixed text color on hover of active element

fix dropdown on project detail

---

adhocracy-plus/assets/scss/components/_account.scss
adhocracy-plus/templates/email_base.subject
adhocracy-plus/templates/email_base.txt
apps/account/emails.py
apps/account/forms.py
apps/account/templates/a4_candy_account/account_dashboard.html
apps/account/templates/a4_candy_account/account_deletion.html
apps/account/templates/a4_candy_account/emails/account_deleted.en.email
apps/account/urls.py
apps/account/views.py
apps/contrib/management/commands/send_test_emails.py
changelog/8104.md
tests/account/test_views.py

First attempt at adding the account deletion submenu
page: http://127.0.0.1:8004/account/account_deletion/
**Tasks**

[8104] apps/accounts: add option to delete account to user profile

---

adhocracy-plus/config/settings/base.py
apps/users/templates/a4_candy_users/indicator.html
changelog/8133.md

The new menu item will appear if the setting APLUS_MANUAL_URL is set. The url will get the language code and ":start" appended to account for the user language.
Testing: in `base.py` change `APLUS_MANUAL_URL`  to `https://manual.adhocracy.plus` and login. The userindicator should now contain a new help menu item.
**Tasks**

[8133] apps/users: add new menu item Help to userindicator

---

adhocracy-plus/templates/includes/project_header_mobile_toggle.html
changelog/2507.md

correctly show the content of each tab.
fixes #2507
**Tasks**

templates: add missing roles to project header mobile toggle to

---

adhocracy-plus/assets/scss/components/_account.scss
adhocracy-plus/assets/scss/components/_button.scss
apps/account/templates/a4_candy_account/account_deletion.html
changelog/8104.md

- adds a new button btn--danger-light which has a lighter red than btn--danger
fixes #2609
**Tasks**

[8104] account deletion: fix button styles not matching the design

---

apps/users/forms.py
changelog/_1113.md

apps/users: disable help text for password field on login page

---

apps/organisations/models.py
changelog/8325.md
tests/organisations/test_organisation_models.py

apps/organisations: change sorting for past projects from oldest -> newst to newest -> oldest (end date).
**Tasks**

apps/organisations: change sorting for past projects

---

adhocracy-plus/assets/scss/components/_a4-comments.scss
adhocracy-plus/assets/scss/components/_dropdown.scss
adhocracy-plus/assets/scss/components/_rating.scss
changelog/7864.md
package.json
requirements/base.txt

needs https://github.com/liqd/adhocracy4/pull/1669
**Tasks**

a4-comments: adapt scss to a4 changes after mB redesign

---

apps/projects/api.py
changelog/8304.md
docs/api.md
tests/projects/test_app_project_api.py
tests/projects/test_project_geolocation.py

[8304] Add geolocation tests

---

adhocracy-plus/assets/scss/components/_captcheck.scss

display none styles for it.
Fixes the captcha in the poll for unregistered users
requires https://github.com/liqd/adhocracy4/pull/1690
fixes #2839 
Testing: create new poll and allow unregistered users, open poll in private tab or sign out
**Tasks**

assets/scss: show react captcha text mode correctly by excluding the

---

Makefile
changelog/_0002.md

Added this as I keep forgetting the exact command, this way I can autocomplete it :)
**Tasks**

Makefile: add docs command to see documentation

---

adhocracy-plus/assets/js/init-picker.js

- selecting a start date in a later month than the end date wouldn't move the end date picker to the new month
- remove the possibility to select a start date past the current end date
**Tasks**

assets/js: make new flatpickr language aware and fix some small issues

---

adhocracy-plus/assets/scss/components/_info_box.scss
adhocracy-plus/assets/scss/style.scss
adhocracy-plus/templates/a4modules/includes/module_description.html
adhocracy-plus/templates/a4modules/module_detail.html
adhocracy-plus/templates/a4polls/includes/unregistered-users-info-box.html
apps/projects/templates/a4_candy_projects/project_detail.html
changelog/8499.md

- created new snippet for the box
- refactored the module description to remove duplicates and make it more maintainable

[#8499] a4-polls: create info box for unregistered users

---

adhocracy-plus/config/settings/base.py

Enable the option to create open polls by default (I don't really see a reason not to allow it by default).
**Tasks**

settings/base.py: enable new open poll feature by default

---

package.json

They already released a fixed version, so we don't need the workaround any more
**Tasks**

remove stylelint workaround

---

apps/cms/contacts/models.py
apps/users/forms.py
changelog/_0001.md

- make contact form and signup use the same captcha helptext and replace the broken <br> tag with <strong>.
fixes #2843
**Tasks**

apps/cms: change helptext for captcha on contact form

---

apps/users/forms.py
changelog/232.md

[STS-232](https://app.asana.com/1/1175467295883992/inbox/1209159381077685/item/1210053730373688/story/1210451705078056)
Adds captcha to the end of the SSO flow: after authentication with eg facebook, but before a new account is created.
I expect this to work, but have not tested because it's tricky to do it locally. Proposing we test on dev if we have a test facebook environment ready there? 
There are also no existing tests for SSO afaik, for the same reason.

users: add captcha for SSO registration

---

adhocracy-plus/templates/socialaccount/signup.html

STS-232
Adds to https://github.com/liqd/adhocracy-plus/pull/2951 https://github.com/liqd/adhocracy-plus/pull/2953 #2954 
Captcha is rendering now, but twice. The widget is inherits from `widgets.HiddenInput` because it has a hidden field, but on social signup what's different from [regular signup](https://github.com/liqd/adhocracy-plus/blob/f61a8c5dadd1764129d04d504267049d711c95af/adhocracy-plus/templates/account/signup.html) is we're using a hidden field to collect the email address. This fix skips over the captcha when rendering hidden fields, so we only render the captcha when it appears later in the form template.

templates: fix social captcha rendered twice

---

adhocracy-plus/assets/scss/components/_datepicker.scss
adhocracy-plus/templates/a4dashboard/base_dashboard_project.html
apps/userdashboard/assets/js/a4_candy_userdashboard/ModerationFeedbackForm.jsx
changelog/8407.md
changelog/845.md

Fixes toward [milestone](https://github.com/liqd/adhocracy-plus/issues?q=is%3Aissue%20state%3Aopen%20milestone%3A%22release%20july%202025%22):
Dashboard: phase datepicker lets user accidentally select entire page
https://github.com/liqd/adhocracy-plus/issues/2837 / https://app.asana.com/1/1175467295883992/project/1209245838104549/task/1210876321384674?focus=true
Dashboard: bug where location / ort dashboard module shows up when switching to german language
https://github.com/liqd/adhocracy-plus/issues/2938 / https://app.asana.com/1/1175467295883992/project/1209245838104549/task/1210868049976111?focus=true
Depends on a4 PR: https://github.com/liqd/adhocracy4/pull/1803
Moderator feedback comment textarea limit to 500 characters
https://github.com/liqd/adhocracy-plus/issues/2708 / …

fixes for datepicker, moderator feedback, location module

---

adhocracy-plus/assets/js/init-picker.js
changelog/2967.md

on mobile native, min/max dates weren't being followed, so this changes flatpickr config to disallow native ui on mobile and use the package's ui instead always.
https://github.com/liqd/adhocracy-plus/issues/2838
https://app.asana.com/1/1175467295883992/project/1208559589495764/task/1210876321384671?focus=true

assets/js: use flatpickr non-native ui on mobile
