liqd/adhocracy-plus

adhocracy-plus/assets/js/app.js
adhocracy-plus/assets/js/embed.js

same as in meinberlin (https://github.com/liqd/a4-meinberlin/pull/2596)

assets: fix embed js like in mb

---

adhocracy-plus/assets/scss/components/_embed_layout.scss
apps/embed/templates/a4_candy_embed/embed.html

awaiting decision on frame colour

templates/embed: add logo to embed and style

---

apps/actions/assets/timestamps.js

This broke in 47d1db2b62fb516 or the commit before.

apps/actions: Fix timeago call

---

adhocracy-plus/templates/account/email/password_reset_key.de.email
apps/dashboard/blueprints.py
apps/dashboard/templates/a4_candy_dashboard/includes/module_blueprint_list_tile.html

fixes #15 
fixes #7 
fixes #14

Mn 2019 issue fixes

---

adhocracy-plus/templates/socialaccount/signup.html
apps/users/forms.py

- remove some duplicated code
- show errors if email is already taken

socialaccount: Some more cleanups

---

adhocracy-plus/assets/scss/components/_embed_layout.scss

styling/embed: put borders on inner elements to only scroll inside embed

---

adhocracy-plus/assets/scss/components/_contact_form.scss
adhocracy-plus/assets/scss/components/_main_header.scss
adhocracy-plus/assets/scss/components/_userindicator.scss
apps/cms/contacts/templates/a4_candy_cms_contacts/form_field.html
apps/cms/news/templates/a4_candy_cms_news/news_index_page.html
apps/cms/news/templates/a4_candy_cms_news/news_page.html
apps/cms/use_cases/templates/a4_candy_cms_use_cases/blocks/examples_block.html
apps/cms/use_cases/templates/a4_candy_cms_use_cases/blocks/use_cases_block.html
apps/cms/use_cases/templates/a4_candy_cms_use_cases/use_case_index_page.html
apps/cms/use_cases/templates/a4_candy_cms_use_cases/use_case_page.html
apps/projects/templates/a4_candy_projects/project_detail.html
apps/users/templates/a4_candy_users/indicator.html

The issues are noted down in the commit messages.

styling issues

---

adhocracy-plus/templates/a4dashboard/base_form_module.html
adhocracy-plus/templates/a4dashboard/base_form_project.html
locale/de_DE/LC_MESSAGES/django.po
locale/en_GB/LC_MESSAGES/django.po

a4dashboard: display notification of error on top of form

---

apps/cms/pages/templates/a4_candy_cms_pages/simple_page.html

apps/cms: Don't display title on simple page

---

adhocracy-plus/config/settings/base.py
apps/users/forms.py
locale/de_DE/LC_MESSAGES/django.po
locale/en_GB/LC_MESSAGES/django.po

Mn 2019 11 change login and registration forms

---

adhocracy-plus/templates/includes/header_logo_link.html

templates: Change font weight with utility class in header

---

apps/cms/news/templates/a4_candy_cms_news/news_page.html
apps/cms/pages/templates/a4_candy_cms_pages/simple_page.html
apps/cms/use_cases/templates/a4_candy_cms_use_cases/use_case_page.html

apps/cms: Make captions italic

---

adhocracy-plus/assets/scss/_variables.scss

styling/base: decrease font-sizes for h1, h2, h3 on desktop

---

apps/projects/templates/a4_candy_projects/emails/invite_moderator.en.email
apps/projects/templates/a4_candy_projects/emails/invite_participant.en.email
apps/projects/templates/a4_candy_projects/moderatorinvite_detail.html
apps/projects/templates/a4_candy_projects/participantinvite_detail.html

I think, this should fix the NoReverseMatch. But I couldn't reproduce it. Will try again, but maybe you could as well @rmader or @MagdaN ?

apps/projects: fix next in participant project invite

---

adhocracy-plus/assets/scss/components/_homepage.scss

assets/templates: match max width of wrapper to breakpoint

---

apps/projects/templates/a4_candy_projects/emails/invite_moderator.de.email
apps/projects/templates/a4_candy_projects/emails/invite_moderator.en.email
apps/projects/templates/a4_candy_projects/emails/invite_participant.de.email
apps/projects/templates/a4_candy_projects/emails/invite_participant.en.email
apps/projects/templates/a4_candy_projects/participantinvite_detail.html
locale/de_DE/LC_MESSAGES/django.po
locale/en_GB/LC_MESSAGES/django.po

fixes #117 
fixes #116 
fixes #121
still need english text

locale: Change invitation detail page text

---

adhocracy-plus/assets/scss/components/_a4-comments.scss
apps/debate/templates/a4_candy_debate/subject_detail.html
package.json
requirements/base.txt

will update hash when a4 branch merged

styling for debate module

---

apps/questions/assets/QuestionBox.jsx
apps/questions/templatetags/react_questions.py

apps/questions: Add screen button again

---

apps/projects/rules.py
tests/projects/dashboard_components/test_views_project_moderators.py
tests/projects/dashboard_components/test_views_project_participants.py

apps/projects/rules: Moderators can't edit projects

---

adhocracy-plus/assets/scss/components/_poll.scss
adhocracy-plus/templates/includes/header_language_switch.html
package.json
requirements/base.txt

Pm 2019 12 issue fixes with a4 dependency

---

apps/debate/exports.py
apps/topicprio/exports.py

Exports ratings of comments in debates

---

adhocracy-plus/assets/scss/components/_accordion.scss
adhocracy-plus/assets/scss/components/_background.scss
adhocracy-plus/assets/scss/components/_marked.scss
adhocracy-plus/assets/scss/components/_tile.scss
adhocracy-plus/assets/scss/style.scss
adhocracy-plus/templates/a4ckeditor/collapsible_fragment.html
apps/activities/templates/a4_candy_activities/includes/activity_detail_content.html
apps/budgeting/templates/a4_candy_budgeting/proposal_list.html
apps/cms/pages/templates/a4_candy_cms_pages/blocks/accordeon_block.html
apps/contrib/templates/a4_candy_contrib/component_library.html
apps/debate/templates/a4_candy_debate/subject_list.html
apps/documents/templates/a4_candy_documents/chapter_detail.html
apps/ideas/templates/a4_candy_ideas/idea_list.html
apps/mapideas/templates/a4_candy_mapideas/mapidea_list.html
apps/organisations/templates/organisation_landing_page.html
apps/polls/templates/a4_candy_polls/poll_detail.html
apps/questions/templates/a4_candy_questions/question_module_detail.html
apps/topicprio/templates/a4_candy_topicprio/topic_list.html

… cms and ck accordeons and
components/module: replace with background/bg-- so can be used elsewhere

background for org project list and style info accordeon

---

package.json
requirements/base.txt

deps: update a4

---

apps/budgeting/exports.py
apps/debate/exports.py
apps/debate/templates/a4_candy_debate/includes/subject_list_item.html
apps/debate/templates/a4_candy_debate/subject_detail.html
apps/debate/templates/a4_candy_debate/subject_list.html
apps/documents/exports.py
apps/ideas/exports.py
apps/mapideas/exports.py
apps/polls/exports.py
apps/projects/templatetags/a4_candy_project_tags.py
apps/topicprio/exports.py
locale/de_DE/LC_MESSAGES/django.po
locale/de_DE/LC_MESSAGES/djangojs.po
locale/en_GB/LC_MESSAGES/django.po
locale/en_GB/LC_MESSAGES/djangojs.po
package.json
requirements/base.txt

fixes #267 
and count debating comments for module tile
the update and translations fixes #285 fixes #276

apps/debate: some issues

---

adhocracy-plus/assets/scss/components/_a4-comments.scss
adhocracy-plus/assets/scss/components/_button.scss
adhocracy-plus/assets/scss/components/_creator_count.scss
apps/debate/templates/a4_candy_debate/includes/subject_list_item.html
apps/users/models.py
package.json
requirements/base.txt

Pm 2020 02 avatar fallbacks

---

locale/de_DE/LC_MESSAGES/django.po

awaiting extra text
fixes #323

Pm 2020 02 reg form

---

adhocracy-plus/assets/scss/_base.scss
adhocracy-plus/assets/scss/_variables.scss
adhocracy-plus/assets/scss/components/_accordion.scss
adhocracy-plus/config/settings/base.py
adhocracy-plus/templates/account/signup.html
adhocracy-plus/templates/base.html
adhocracy-plus/templates/header.html
adhocracy-plus/templates/header_dashboard.html
apps/account/templates/a4_candy_account/profile.html
apps/contrib/templatetags/force_translation.py
apps/users/forms.py
locale/de_DE/LC_MESSAGES/django.po
tests/users/test_signup.py
tests/users/test_views.py

Ok I wanted to remove the additional changes that were uneeded but it's listing all commits for some reason?!

Pm 2020 02 rm font size change

---

adhocracy-plus/templates/email_base.html
adhocracy-plus/templates/email_base.txt
package.json
requirements/base.txt

Some more fixes to get emails going. Unfortunately we don't have time to set things up as they are actually supposed to work with the sites framework, but we can handle that later.

templates/email_base: Readd host - we actually do need it

---

adhocracy-plus/config/settings/base.py
apps/users/forms.py
requirements/base.txt

Add custom registration form for IG-BCE

---

locale/de_DE/LC_MESSAGES/django.po

translations/de_DE/django.po: update footer wording

---

adhocracy-plus/assets/scss/components/_a4-comments.scss
adhocracy-plus/assets/scss/components/_list_item.scss
adhocracy-plus/assets/scss/components/_main_header.scss
adhocracy-plus/assets/scss/components/_tile.scss
adhocracy-plus/templates/header.html
adhocracy-plus/templates/header_dashboard.html
apps/projects/templates/a4_candy_projects/includes/project_list_tile.html

Pm 2020 03 general issues

---

apps/contrib/tasks.py
apps/users/forms.py

Use a simple background task to throw the error in question, so we
can monitor them in setry. Note: tasks retries should therefore get
limited to 1, otherwise we will get spammed.

apps/users/forms: Add catchall except for igbce api

---

apps/debate/forms.py

apps/debate: use textarea for subject description in dashboard form

---

apps/contrib/tasks.py
apps/users/forms.py

The previous solution was simply utterly wrong :)

apps/users/forms: Properly log exceptions

---

apps/projects/emails.py

This should fix https://sentry.liqd.net/sentry/aplus-prod/issues/995/

apps/project/emails: Use object as dict

---

adhocracy-plus/config/settings/base.py
adhocracy-plus/templates/footer.html
adhocracy-plus/templates/header.html
apps/organisations/templates/organisation_information.html
locale/de_DE/LC_MESSAGES/django.po

everything has it's own commit so can be put wherever is best

Enquete pm fixes

---

package.json
webpack.common.js

webpack: Readd IE11 support because !*$#@&^

---

apps/contrib/templates/a4_candy_contrib/item_detail.html
apps/debate/templates/a4_candy_debate/subject_detail.html
apps/documents/templates/a4_candy_documents/chapter_detail.html
apps/documents/templates/a4_candy_documents/paragraph_detail.html
apps/polls/templates/a4_candy_polls/poll_detail.html
apps/topicprio/templates/a4_candy_topicprio/topic_detail.html
package.json
requirements/base.txt

this is branch to be tested alongside https://github.com/liqd/adhocracy4/pull/504

Pm 2020 03 comments test

---

apps/contrib/templates/a4_candy_contrib/item_detail.html
apps/debate/templates/a4_candy_debate/subject_detail.html
apps/documents/templates/a4_candy_documents/chapter_detail.html
apps/documents/templates/a4_candy_documents/paragraph_detail.html
apps/polls/templates/a4_candy_polls/poll_detail.html
apps/topicprio/templates/a4_candy_topicprio/topic_detail.html
package.json
requirements/base.txt

Reverts comments testing branch liqd/adhocracy-plus#491

Revert "Pm 2020 03 comments test"

---

apps/maps/assets/map_choose_polygon_with_preset.js

Bootstrap needs to get imported explicitly. Also, add console logs to
make it easier to catch such bugs in the future and work around a
bootstrap bug.

maps/assets: Fix geojson upload

---

apps/account/forms.py

Analogous to https://github.com/liqd/a4-meinberlin/pull/2890

apps/account/forms: Check username for case insensitive uniqueness

---

adhocracy-plus/assets/scss/_layout.scss
adhocracy-plus/assets/scss/components/_dashboard_nav.scss
adhocracy-plus/assets/scss/components/_follow.scss
adhocracy-plus/assets/scss/components/_footer.scss
adhocracy-plus/assets/scss/components/_header_lower.scss
adhocracy-plus/assets/scss/components/_participation-tile.scss
adhocracy-plus/assets/scss/components/_project_header.scss
adhocracy-plus/assets/scss/components/_tile.scss
adhocracy-plus/templates/a4dashboard/base_dashboard.html
adhocracy-plus/templates/a4modules/module_detail.html
apps/budgeting/templates/a4_candy_budgeting/proposal_create_form.html
apps/budgeting/templates/a4_candy_budgeting/proposal_list.html
apps/budgeting/templates/a4_candy_budgeting/proposal_moderate_form.html
apps/budgeting/templates/a4_candy_budgeting/proposal_update_form.html
apps/contrib/templates/a4_candy_contrib/item_detail.html
apps/debate/templates/a4_candy_debate/subject_detail.html
apps/ideas/templates/a4_candy_ideas/idea_create_form.html
apps/ideas/templates/a4_candy_ideas/idea_moderate_form.html
apps/ideas/templates/a4_candy_ideas/idea_update_form.html
apps/mapideas/templates/a4_candy_mapideas/mapidea_create_form.html
apps/mapideas/templates/a4_candy_mapideas/mapidea_moderate_form.html
apps/mapideas/templates/a4_candy_mapideas/mapidea_update_form.html
apps/organisations/templates/a4_candy_organisations/organisation_information.html
apps/organisations/templates/a4_candy_organisations/organisation_landing_page.html
apps/polls/templates/a4_candy_polls/poll_detail.html
apps/projects/templates/a4_candy_projects/project_detail.html

I think that's everywhere now! (I hope)

Pm 2020 04 org mobile

---

adhocracy-plus/assets/scss/components/_footer.scss
adhocracy-plus/assets/scss/components/_header_lower.scss
adhocracy-plus/templates/footer_upper.html

I just did it like that (for now) and then @mcastro-lqd can have a say, when it's merged or when he reviews the whole header/footer story? I left out the active-stuff because I think it is unusual to have that in a footer.

templates/upper footer: style links

---

adhocracy-plus/assets/js/app.js

drive by cleanups

---

renovate.json

settings/renovate: disable automerge for minor versions

---

adhocracy-plus/assets/js/app.js
adhocracy-plus/assets/scss/components/_dashboard_nav.scss
adhocracy-plus/assets/scss/components/_dropdown.scss
adhocracy-plus/templates/a4dashboard/base_dashboard_project.html
apps/cms/use_cases/templates/a4_candy_cms_use_cases/use_case_index_page.html
apps/contrib/templates/a4_candy_contrib/component_library.html
apps/users/templates/a4_candy_users/indicator.html

@fuzzylogic2000 this currently works as there is only 1 module but when there are more then 1 I'll need to add unique id to module menus

Pm 2020 04 dashboard left

---

adhocracy-plus/assets/scss/_shame.scss
adhocracy-plus/assets/scss/_variables.scss
adhocracy-plus/assets/scss/components/_button.scss
adhocracy-plus/assets/scss/components/_header_upper.scss
adhocracy-plus/assets/scss/components/_language_switch.scss
adhocracy-plus/assets/scss/components/_timeline-carousel.scss
adhocracy-plus/assets/scss/components/_userindicator.scss
adhocracy-plus/assets/scss/platform.scss
adhocracy-plus/templates/500.html
adhocracy-plus/templates/base.html
adhocracy-plus/templates/header.html
adhocracy-plus/templates/includes/header_language_switch.html
adhocracy-plus/templates/includes/header_mobile_toggle.html
apps/users/templates/a4_candy_users/indicator.html
webpack.common.js

Pm 2020 05 replace language switch and header refactor

---

adhocracy-plus/assets/scss/components/_alerts.scss
adhocracy-plus/templates/account/signup.html
adhocracy-plus/templates/base.html
adhocracy-plus/templates/email_base.html
adhocracy-plus/templates/socialaccount/signup.html
apps/topicprio/templates/a4_candy_topicprio/topic_detail.html
apps/users/forms.py

translations removed async  comments stuff again so didn't add them in this pull request will try after this is merged

Pm 2020 05 issue fixes

---

adhocracy-plus/assets/scss/_layout.scss
adhocracy-plus/assets/scss/components/_alerts.scss
adhocracy-plus/assets/scss/components/_button.scss
adhocracy-plus/assets/scss/components/_dropdown.scss
adhocracy-plus/assets/scss/components/_list_item.scss
adhocracy-plus/assets/scss/components/_tabs.scss
adhocracy-plus/assets/scss/components/_tile.scss
adhocracy-plus/templates/a4dashboard/base_dashboard.html
adhocracy-plus/templates/a4dashboard/base_dashboard_project.html
adhocracy-plus/templates/a4dashboard/base_project_list.html
adhocracy-plus/templates/a4images/image_upload_widget.html
adhocracy-plus/templates/base.html
apps/dashboard/templates/a4_candy_dashboard/includes/module_blueprint_list_tile.html
apps/dashboard/templates/a4_candy_dashboard/module_blueprint_list.html
locale/de_DE/LC_MESSAGES/django.po
locale/de_DE/LC_MESSAGES/djangojs.po
locale/en_GB/LC_MESSAGES/django.po
locale/en_GB/LC_MESSAGES/djangojs.po

will add translations in next pull request once sorted weird deleations
fixes #604

Pm 2020 05 multi mod issues

---

adhocracy-plus/templates/a4dashboard/base_dashboard_project.html
apps/dashboard/views.py

Ka 2020 05 delete modules

---

apps/budgeting/templates/a4_candy_budgeting/proposal_list.html

This copies over some changes made to the corresponding mapideas template,
most importantly fixes from 316c0017, 7eced573b and b3ed08ace.

apps/budgeting/templates: Adapt to mapideas template changes

---

apps/budgeting/templates/a4_candy_budgeting/proposal_list.html

forgot to add template logic when updating other maps, sorry!

budgeting/proposal_list: adding logic to display ratings for mmap points

---

locale/nl_NL/LC_MESSAGES/django.po
locale/nl_NL/LC_MESSAGES/djangojs.po
locale/tr_TR/LC_MESSAGES/django.po
locale/tr_TR/LC_MESSAGES/djangojs.po

Pull translations from transifex before pushing new email translation strings.

Ks 2020 06 pull translations from transifex

---

README.md

Todo:
- install guide
- update guide
- extra `make` commands?
- maybe some cleaups

README: Add deployment documentation

---

adhocracy-plus/assets/scss/_variables.scss
apps/budgeting/templates/a4_candy_budgeting/proposal_list.html
apps/debate/templates/a4_candy_debate/subject_detail.html
apps/ideas/templates/a4_candy_ideas/idea_create_form.html
apps/ideas/templates/a4_candy_ideas/idea_list.html
apps/mapideas/templates/a4_candy_mapideas/mapidea_create_form.html
apps/mapideas/templates/a4_candy_mapideas/mapidea_list.html
apps/organisations/templates/a4_candy_organisations/organisation_information.html
apps/organisations/templates/a4_candy_organisations/organisation_landing_page.html
apps/projects/templates/a4_candy_projects/project_detail.html

little front end fixes that came up during clean

Pm 2020 07 tiny fix

---

README.md
adhocracy-plus/config/settings/base.py

closes https://github.com/liqd/adhocracy-plus/issues/702

README.md: Update installation guide

---

README.md
docs/installation_prod.md

Docs updates

---

.travis.yml
Makefile
apps/organisations/apps.py
apps/projects/apps.py
package.json
requirements/dev.txt

I am not convinced it's faster but it does seem to be doing what it's meant to, my script might be wrong though?!
Oh and need to do a make install, i forgot that when coming back to test :p

Pm 2020 isort test

---

apps/contrib/templatetags/settings.py

It allows to query settings - useful hack for all kinds of things
in templates.

apps/contrib: Add templatetag for settings

---

docs/installation_prod.md

docs: Add shibolleth docu for DIID

---

adhocracy-plus/config/urls.py
apps/questions/templatetags/react_questions.py

So we don't need nginx rewrites to make this work for organisations
with own domains.

apps/questions: Use organisation slug

---

tests/questions/conftest.py
tests/questions/factories.py
tests/questions/rules/test_rules_change.py
tests/questions/rules/test_rules_moderate.py
tests/questions/rules/test_rules_propose.py
tests/questions/rules/test_rules_view.py
tests/questions/test_question_api.py
tests/questions/test_question_model.py
tests/questions/test_question_templatetags.py
tests/questions/views/test_question_create.py
tests/questions/views/test_question_presentation_list.py

Coverage +1.2% :partying_face:

tests: add tests for questions

---

apps/questions/assets/QuestionBox.jsx
apps/questions/templates/a4_candy_questions/question_module_detail.html

small changes for Monday if possible

apps/questions: style module info and phase info to be more readable

---

adhocracy-plus/templates/base.html
apps/contrib/templates/a4_candy_contrib/matomo/tracking_code.html
apps/contrib/templatetags/contrib_tags.py

Enable the ability to add matomo tracking and add no-cookie option.

Matomo tracking

---

adhocracy-plus/config/settings/base.py

lets hope, that this was the problem! it works on local at least..
fixes #827

settings: disable parler caching

---

package.json

Reverts liqd/adhocracy-plus#788
fixes #853

Revert "fix(deps): update dependency leaflet to v1.7.1"

---

package.json

Reverts liqd/adhocracy-plus#843

Revert "fix(deps): update dependency webpack to v5"

---

package.json

Reverts liqd/adhocracy-plus#851

Revert "fix(deps): update dependency terser-webpack-plugin to v5"

---

apps/djangosaml2_overwrites/forms.py
apps/djangosaml2_overwrites/templates/djangosaml2_overwrites/signup.html

And to expose the get_notification option.

djangosaml2_overwrites: Adapt form to match signup

---

adhocracy-plus/config/settings/base.py
locale-fork/locale/de_DE/LC_MESSAGES/django.po
locale-fork/locale/de_DE/LC_MESSAGES/djangojs.po
locale-fork/locale/en_GB/LC_MESSAGES/django.po
locale-fork/locale/en_GB/LC_MESSAGES/djangojs.po
locale-fork/locale/nl_NL/LC_MESSAGES/django.po
locale-fork/locale/nl_NL/LC_MESSAGES/djangojs.po
locale-fork/locale/tr_TR/LC_MESSAGES/django.po
locale-fork/locale/tr_TR/LC_MESSAGES/djangojs.po
locale-source/locale/de_DE/LC_MESSAGES/django.po

I think, we can now add all missing for DIID to the locale-fork folder and we should be fine!

Ka 2020 11 translations diid

---

docs/translations.md

I think this is right, @Rineee please feel free to correct me?!

docs: add transifex documentation

---

adhocracy-plus/templates/email_base.html

Pm diid 2020 11 email logo

---

tests/debate/views/test_subject_detail.py
tests/ideas/views/test_idea_detail.py
tests/mapideas/views/test_mapidea_detail.py
tests/organisations/test_organisation_detail_view.py
tests/topicprio/views/test_topic_detail.py

The main tests are about whether users can comment or not.

Test for semipublic projects

---

apps/organisations/sitemaps.py

fixes https://sentry.liqd.net/sentry/aplus-prod/issues/1256/

organisations/sitemaps: fixup for using the new access enum

---

adhocracy-plus/templates/a4modules/module_detail.html
adhocracy-plus/templates/footer_upper.html
adhocracy-plus/templates/header_lower.html
apps/budgeting/templates/a4_candy_budgeting/proposal_create_form.html
apps/budgeting/templates/a4_candy_budgeting/proposal_update_form.html
apps/contrib/templates/a4_candy_contrib/item_detail.html
apps/debate/templates/a4_candy_debate/subject_detail.html
apps/ideas/templates/a4_candy_ideas/idea_create_form.html
apps/ideas/templates/a4_candy_ideas/idea_moderate_form.html
apps/ideas/templates/a4_candy_ideas/idea_update_form.html
apps/mapideas/templates/a4_candy_mapideas/mapidea_create_form.html
apps/mapideas/templates/a4_candy_mapideas/mapidea_moderate_form.html
apps/mapideas/templates/a4_candy_mapideas/mapidea_update_form.html
apps/organisations/templates/a4_candy_organisations/organisation_data_protection.html
apps/organisations/templates/a4_candy_organisations/organisation_imprint.html
apps/organisations/templates/a4_candy_organisations/organisation_information.html
apps/organisations/templates/a4_candy_organisations/organisation_landing_page.html
apps/organisations/templates/a4_candy_organisations/organisation_netiquette.html
apps/organisations/templates/a4_candy_organisations/organisation_terms_of_use.html
apps/projects/templates/a4_candy_projects/project_detail.html

A better solution for #933 and also including the footer_lower
But should go into the release after the next one, to be tested on dev for a while!

templates/header_lower & footer_upper: always use organisation from view

---

apps/projects/views.py
tests/projects/dashboard_components/test_views_project_moderators.py
tests/projects/dashboard_components/test_views_project_participants.py

fixes https://sentry.liqd.net/sentry/aplus-prod/issues/932/

apps/projects: error handling for deleted invitations

---

adhocracy-plus/templates/a4modules/module_detail.html
apps/projects/templates/a4_candy_projects/project_detail.html
locale-source/locale/de/LC_MESSAGES/django.po
locale-source/locale/en/LC_MESSAGES/django.po
locale-source/locale/nl/LC_MESSAGES/django.po
locale-source/locale/tr/LC_MESSAGES/django.po

translations: Fix a spelling error

---

locale-source/locale/de/LC_MESSAGES/django.po

translations: Dein Profil -> Ihr Profil

---

adhocracy-plus/assets/scss/components/_live_questions.scss
apps/interactiveevents/assets/js/a4_candy_interactive_events/livequestion_category_select.jsx
apps/interactiveevents/assets/js/a4_candy_interactive_events/livequestion_form.jsx

Tried to style it, but didnt really succeed.. @phillimorland I think there is padding missing inside the select box, but couldnt figure out how to do it, could only always add padding around the box :grimacing:

Ks 2020 12 move livequestion category select to own component

---

apps/projects/templates/a4_candy_projects/project_detail.html

like https://github.com/liqd/a4-meinberlin/pull/3331

apps/projects: only show private info for modules, not events

---

apps/cms/contacts/models.py

fixes #1129
But to not make the migration run without the changes, we might need to change the history of master :grimacing: @rmader Can we have a look together?

cms/wagtail: add new fields for wagtails AbstractFormField

---

adhocracy-plus/config/settings/base.py
adhocracy-plus/config/settings/test.py
adhocracy-plus/templates/account/signup.html
apps/captcha/mixins.py
apps/users/forms.py
tests/users/test_signup.py
tests/users/test_views.py

This should be enough to start working on the DB - we can add the more complicated wagtail form captcha stuff later.

Kl 2021 02 captcha

---

docs/languages_and_translations.md

I tried pushing new strings without pulling translations first and translations get not lost, to I updated the docs

docs: update transifex procedure

---

package.json
webpack.common.js

Reverts liqd/adhocracy-plus#1154

Revert "fix(deps): update dependency copy-webpack-plugin to v8"

---

locale-source/locale/de/LC_MESSAGES/django.po
locale-source/locale/de/LC_MESSAGES/djangojs.po
locale-source/locale/en/LC_MESSAGES/django.po
locale-source/locale/en/LC_MESSAGES/djangojs.po
locale-source/locale/ky/LC_MESSAGES/django.po
locale-source/locale/ky/LC_MESSAGES/djangojs.po
locale-source/locale/nl/LC_MESSAGES/django.po
locale-source/locale/nl/LC_MESSAGES/djangojs.po
locale-source/locale/ru/LC_MESSAGES/django.po
locale-source/locale/ru/LC_MESSAGES/djangojs.po
locale-source/locale/tr/LC_MESSAGES/django.po
locale-source/locale/tr/LC_MESSAGES/djangojs.po

New po files as pushed to transifex and few translations to German pulled from transifex

Kl 2021 04 new strings

---

adhocracy-plus/assets/scss/_utility.scss
adhocracy-plus/assets/scss/components/_button.scss
adhocracy-plus/assets/scss/components/_label.scss
apps/contrib/templates/a4_candy_contrib/component_library.html
apps/interactiveevents/templates/a4_candy_interactive_events/module_detail.html
apps/projects/templates/a4_candy_projects/project_detail.html

Using the new module property extra_fields.event_image to show
an event image if existing. Re-layouting detail screen (also
for mobile).
WIP: function of 'read more' button to be discussed.

module/interactiveevent: showing optional event image

---

tests/dashboard/test_dashboard_views.py
tests/interactiveevents/dashboard_components/test_interactiveevent_media_component.py
tests/interactiveevents/rules/test_rules_like.py
tests/interactiveevents/views/test_interactiveevent_module_detail.py

There is much more to test, maybe for Monday :)

Ks 2021 05 adding tests

---

package.json

Reverts liqd/adhocracy-plus#1278

Revert "chore(deps): update dependency lint-staged to v11"

---

adhocracy-plus/assets/scss/components/_label.scss
adhocracy-plus/assets/scss/components/_live_questions.scss
apps/interactiveevents/templates/a4_candy_interactive_events/module_detail.html
apps/projects/templates/a4_candy_projects/project_detail.html
package.json
requirements/base.txt

depends on: https://github.com/liqd/adhocracy4/pull/720

module/interactiveevents: image path

---

adhocracy-plus/templates/a4modules/module_detail.html
apps/projects/templates/a4_candy_projects/project_detail.html

I don't think, we should treat only that one module type so differently by checking for the phases... I added a FIXME to the commit message and will also add an issue.
fixes #1263 (the last thing to fix: 4.)

Kl 2021 05 double phase content

---

apps/ideas/api.py
apps/ideas/serializers.py

@khamui  Can you work with the format of the date?

ideas/serializers: add creator and created to serializer

---

adhocracy-plus/config/urls.py
apps/projects/admin.py
apps/projects/api.py
apps/projects/serializers.py
package.json
requirements/base.txt

Just tell me if we need more fields or I added unnecessary stuff :)
Available under /api/app-projects

Ks 2021 05 add app accessible projects api

---

apps/ideas/api.py
apps/ideas/serializers.py

curl command to test are
`curl -X POST http://localhost:8004/api/modules/$moduleId/ideas/ -H 'Accept: application/json;' -u email:password -d 'name=an idea&description=sent by curl&category_pk=$category_pk&labels=$label_pk_1&labels=$label_pk_2'`
to post a new idea and to edit an existing one 
`curl -X PUT http://localhost:8004/api/modules/$module_pk/ideas/$idea_pk/ -H 'Accept: application/json;' -u email:password -d 'name=new name&description=new description'`

ideas/api//serializers: make post and put possible

---

apps/projects/serializers.py

@khamui Sorry for the confusion, now its returning the orga name

projects/serializers: return orga name in app project serializer

---

adhocracy-plus/config/settings/base.py
adhocracy-plus/config/urls.py
apps/ideas/serializers.py

Needs make install to run migrations.
To generate a token (or get an existing one), do
`curl -X POST http://localhost:8004/api/login/ -H 'Accept: application/json;' -d 'username=$username&password=$password'`
You can use username or email as username. The api should give you back a token, that you can also see in django admin. Then use this token to post
`curl -X POST http://localhost:8004/api/modules/$moduleId/ideas/ -H 'Accept: application/json;' -H 'Authorization: Token $token' -d 'name=my name&description=my description'`

Ks 2021 06 use rest auth token for api

---

adhocracy-plus/config/urls.py
apps/projects/api.py
apps/projects/serializers.py

I didn't do it with different Module serializers for different module types after all. And I hope, it all makes sense. :)

apps/projects: add api for module and phase info to be used in app

---

docs/django_shell_basics.md

Can be probably be improved further, but its a start..

docs: add django shell basics

---

apps/ideas/serializers.py

needed for https://github.com/liqd/zt-app/pull/88

ideas/serializers: use right category key from request context in create

---

adhocracy-plus/assets/scss/components/_progress.scss
adhocracy-plus/templates/a4dashboard/includes/progress_line.html
adhocracy-plus/templates/a4dashboard/includes/progress_line_done.html
apps/contrib/templates/a4_candy_contrib/component_library.html
apps/dashboard/templates/a4_candy_dashboard/includes/progress.html
apps/dashboard/templatetags/a4_candy_dashboard_tags.py

I based the progress bar styling (https://app.zeplin.io/project/5b051f895f8bcd4920567e89/screen/5ea1b440bcdcdd7a3d91c493), but I don't know how to make the circle as it should be "in-progress". @phillimorland maybe you can have a look?

apps/dashboard: changed progress functionality to progress bar

---

adhocracy-plus/templates/a4dashboard/base_dashboard_project.html

dashboard/editpolls/save: adding selector to nav to update on success

---

apps/contrib/templates/a4_candy_contrib/component_library.html

fixes https://sentry.liqd.net/organizations/liqd/issues/1624/?project=30

component library: remove translation tags

---

Makefile
locale-source/locale/de/LC_MESSAGES/django.po
locale-source/locale/de/LC_MESSAGES/djangojs.po
locale-source/locale/en/LC_MESSAGES/django.po
locale-source/locale/en/LC_MESSAGES/djangojs.po
locale-source/locale/ky/LC_MESSAGES/django.po
locale-source/locale/ky/LC_MESSAGES/djangojs.po
locale-source/locale/nl/LC_MESSAGES/django.po
locale-source/locale/nl/LC_MESSAGES/djangojs.po
locale-source/locale/ru/LC_MESSAGES/django.po
locale-source/locale/ru/LC_MESSAGES/djangojs.po
locale-source/locale/tr/LC_MESSAGES/django.po
locale-source/locale/tr/LC_MESSAGES/djangojs.po

Fixes #1585
The makefile is
1. fixed in the first commit 
2. applied in the second commit with a pull from transifex. This was then also pushed to transifex.
as discusssed [here](https://github.com/liqd/adhocracy-plus/pull/1586#pullrequestreview-812165389) .
A safety branch of the status of transifex was created beforehand [here](https://github.com/liqd/adhocracy-plus/tree/sm-2021-11-transifex-safety).

Sm 2021 11 fix make translations

---

adhocracy-plus/config/settings/base.py

fixes #1546 
But let's see if we need it or if the server setting changes are sufficient.

settings: add variables for ck editor embed provider

---

adhocracy-plus/config/settings/base.py

Reverts liqd/adhocracy-plus#1623

Revert "settings: add variables for ck editor embed provider"

---

apps/users/emails.py
package.json
requirements/base.txt

depending on a4: https://github.com/liqd/adhocracy4/pull/952 - only merge when updated
fixes #130

apps/emails: move get_site for organisation to a4

---

adhocracy-plus/config/settings/dev.py
adhocracy-plus/config/settings/production.py

needs to be merged with changes in admin

config: set ckeditor provider from local.py

---

apps/contrib/rules.py
tests/comments/conftest.py
tests/comments/rules/test_rules_change_comment.py
tests/comments/test_async_api.py

apps/rules: only owner can edit comment

---

apps/newsletters/templates/a4_candy_newsletters/emails/newsletter_email.en.email
apps/notifications/templatetags/verbose_name.py
tests/conftest.py
tests/notifications/conftest.py
tests/notifications/test_creator_notifications.py
tests/notifications/test_follow_signals.py
tests/notifications/test_follower_notifications.py
tests/notifications/test_initiator_notifications.py
tests/notifications/test_moderator_notifications.py

After merging and rebasing, we can also add the tests for the new notifications in kosmo...

tests/notifications: add tests for notifications

---

adhocracy-plus/config/settings/test.py
apps/newsletters/forms.py
package.json
requirements/base.txt
tests/newsletters/conftest.py
tests/newsletters/factories.py
tests/newsletters/test_newsletter_models.py
tests/newsletters/test_newsletter_views.py

- adds newsletter tests
- second commit is a4-depending (needs to be updated after https://github.com/liqd/adhocracy4/pull/1057 is merged) -> done and fine!
My explanation about why it did not work was all wrong. Bit now it does work and fixes the issue!

Kl 2022 04 newsletter project

---

requirements/base.txt
requirements/dev.txt
requirements/prod.txt

* use psycopg2 for prod
* use psycopg2-binary for dev

requirements: use different psycopg2 flavors

---

adhocracy-plus/assets/scss/components/_accordion.scss

apps/dashboard_project/richtext collapsible: fixes #1811

---

adhocracy-plus/config/settings/base.py
adhocracy-plus/config/urls.py

Belongs to https://github.com/liqd/adhocracy4/pull/1107 and needs update of a4 hash after that is merged

settings/base: add A4_USE_ORGANISATIONS_TERMS_OF_USE

---

requirements/base.txt

- see https://github.com/justinmayer/django-autoslug/issues/78

deps: use own autoslug repo with fix for trailing dash

---

adhocracy-plus/templates/a4dashboard/base_dashboard.html
apps/contrib/templates/a4_candy_contrib/component_library.html
package.json
tests/users/test_views.py

* change email to liqd.net
* fix deprecation of ifequals

Jd 2022 07 change email

---

apps/projects/serializers.py
tests/dashboard/test_dashboard_views_project_create.py
tests/projects/test_app_module_api.py
tests/projects/test_app_project_api.py

Sorry that there is so much different stuff in there :see_no_evil: 
The first 2 commits are about blueprint types and the last 3 are connected to zt issues and [this PR](https://github.com/liqd/zt-app/pull/346).
Also fixes https://github.com/liqd/zt-app/issues/317

Ks 2022 07 module type tests and fixes

---

adhocracy-plus/config/urls.py
apps/account/api.py
apps/account/serializers.py

This allows PUT or GET on api/account/ and operates on the logged in user, if no authenticated user, returns 401.

account//config/urls: add account api and viewset

---

apps/account/serializers.py
apps/users/serializers.py
package.json
requirements/base.txt
tests/account/test_api.py
tests/comments/test_async_serializer.py

The update a4 commit is to be able to show images and fallback images in comments in the app.
So depends on https://github.com/liqd/adhocracy4/pull/1176 and **hash needs update after that is merged**.

Ks 2022 08 add images app user serializers

---

Makefile

add makefile option to easily set a4 to local in package.json and requirements/base. Needs the a4 repo to be in the parent folder / `../adhocracy4`

Jd 2022 08 local a4

---

webpack.common.js

Reverts liqd/adhocracy-plus#2111

Revert "webpack.common: update to maplibre -test"

---

adhocracy-plus/assets/scss/_form.scss
adhocracy-plus/assets/scss/components/_blocks.scss
adhocracy-plus/assets/scss/components/_button.scss
adhocracy-plus/assets/scss/components/_commenting.scss
adhocracy-plus/assets/scss/components/_header_upper.scss
adhocracy-plus/assets/scss/components/_lr_bar.scss
adhocracy-plus/assets/scss/components/_upload.scss
adhocracy-plus/templates/a4images/image_upload_widget.html
adhocracy-plus/templates/a4modules/module_detail.html
apps/cms/pages/templates/a4_candy_cms_pages/blocks/col_cta_block.html
apps/projects/templates/a4_candy_projects/project_list.html
apps/users/templates/a4_candy_users/user_detail.html

Pm 2022 12 styling issues

---

adhocracy-plus/assets/scss/components/_item_detail.scss

components/item_detail.scss: setting item detail's z-index

---

apps/cms/pages/models.py
apps/organisations/forms.py
apps/organisations/templates/a4_candy_organisations/organisation_landing_page.html

1st commit fixes https://sentry.liqd.net/organizations/liqd/issues/2841/?project=30
3rd commit fixes https://sentry.liqd.net/organizations/liqd/issues/2874/?project=30

Ks 2022 12 issues

---

apps/organisations/forms.py
apps/organisations/views.py
tests/conftest.py
tests/organisations/test_organisation_communication_content_views.py
tests/organisations/test_organisation_communication_forms.py

~~Setting this to WIP as it would be broken after image stuff is merged.. so will continue then.~~

Ks 2022 12 communication form tests

---

adhocracy-plus/templates/account/email.html
apps/budgeting/templates/a4_candy_budgeting/proposal_list.html
apps/budgeting/views.py
apps/debate/templates/a4_candy_debate/subject_dashboard_list.html
apps/debate/templates/a4_candy_debate/subject_list.html
apps/debate/views.py
apps/ideas/templates/a4_candy_ideas/idea_list.html
apps/ideas/views.py
apps/mapideas/templates/a4_candy_mapideas/mapidea_list.html
apps/mapideas/views.py
apps/offlineevents/templates/a4_candy_offlineevents/offlineevent_list.html
apps/organisations/templates/a4_candy_organisations/communication_form_social_media.html
apps/topicprio/templates/a4_candy_topicprio/topic_dashboard_list.html
apps/topicprio/templates/a4_candy_topicprio/topic_list.html
apps/topicprio/views.py
apps/users/adapters.py

The third commit fixes  #1073 as this error happens, because the subjects dont get annotated (the annotation happens in the filter and if the filter argument is invalid, it doesnt get there). Then, when adding the annotations, I thought, I could also move the filtering for module to the parent class, but that actually broke the .count in the template :woman_shrugging:  Now it uses for/empty tags which works!

Ks 2022 12 more issues

---

adhocracy-plus/assets/scss/_form.scss
adhocracy-plus/assets/scss/_variables.scss
adhocracy-plus/assets/scss/components/_button.scss
adhocracy-plus/assets/scss/components/_ck_video_embed.scss
adhocracy-plus/assets/scss/components/_copyright.scss
adhocracy-plus/assets/scss/components/_dashboard_nav.scss
adhocracy-plus/assets/scss/components/_datepicker.scss
adhocracy-plus/assets/scss/components/_editpoll.scss
adhocracy-plus/assets/scss/components/_footer.scss
adhocracy-plus/assets/scss/components/_header_upper.scss
adhocracy-plus/assets/scss/components/_label.scss
adhocracy-plus/assets/scss/components/_live_questions.scss
adhocracy-plus/assets/scss/components/_poll.scss
adhocracy-plus/assets/scss/components/_project_header.scss
adhocracy-plus/assets/scss/components/_style_guide.scss
adhocracy-plus/templates/a4dashboard/base_dashboard.html
adhocracy-plus/templates/base.html
apps/contrib/templates/a4_candy_contrib/component_library.html

[issues] styling issues 

---

package.json

fixes webpack build error and console warnings

add maplibregl-mapbox-request-transformer

---

adhocracy-plus/config/settings/base.py
locale-source/locale/de/LC_MESSAGES/django.po
locale-source/locale/en/LC_MESSAGES/django.po
locale-source/locale/hu/LC_MESSAGES/django.po
locale-source/locale/ky/LC_MESSAGES/django.po
locale-source/locale/nl/LC_MESSAGES/django.po
locale-source/locale/ru/LC_MESSAGES/django.po
locale-source/locale/tr/LC_MESSAGES/django.po

@fuzzylogic2000 Could you add the makemessages again? It is still doing the weird thing with the abbreviations for me :woman_shrugging: Also, do we want to add the strings uppercase here already? Wasnt sure..
fixes  #2235

settings/base: change wording of a4_blueprint_types

---

adhocracy-plus/assets/scss/_shame.scss

Decided to fix it here instead of adding classes in a4.

assets/shame: make sure comment buttons are styled

---

apps/userdashboard/api.py
apps/userdashboard/assets/js/a4_candy_userdashboard/ModerationFeedback.jsx
apps/userdashboard/assets/js/a4_candy_userdashboard/ModerationNotification.jsx
apps/userdashboard/assets/js/a4_candy_userdashboard/ModerationNotificationActionsBar.jsx
apps/userdashboard/assets/js/a4_candy_userdashboard/ModerationNotificationList.jsx
apps/userdashboard/assets/js/a4_candy_userdashboard/__tests__/ModerationFeedback.jest.jsx
apps/userdashboard/assets/js/a4_candy_userdashboard/__tests__/ModerationNotificationActionsBar.jest.jsx
apps/userdashboard/serializers.py
package.json
requirements/base.txt

[7210, 7213] Ks 2023 04 filter for reviewed comments

---

apps/projects/api.py
apps/projects/helpers.py
apps/projects/serializers.py
apps/userdashboard/assets/js/a4_candy_userdashboard/ModerationProjects.jsx
apps/userdashboard/views.py
apps/users/models.py

this should help at least a little with the very slow userdashboard

userdashboard: improve db queries for actions

---

adhocracy-plus/assets/scss/components/_button.scss
adhocracy-plus/assets/scss/components/_list_item.scss
adhocracy-plus/templates/a4dashboard/includes/project_list_item.html
apps/budgeting/templates/a4_candy_budgeting/includes/proposal_list_item.html
apps/budgeting/templates/a4_candy_budgeting/proposal_detail.html
apps/contrib/templates/a4_candy_contrib/component_library.html
apps/contrib/templates/a4_candy_contrib/item_detail.html
apps/ideas/templates/a4_candy_ideas/includes/idea_list_item.html
apps/interactiveevents/assets/Filters.jsx
apps/interactiveevents/assets/QuestionBox.jsx
apps/interactiveevents/templates/a4_candy_interactive_events/livequestion_module_detail.html
apps/interactiveevents/templates/a4_candy_interactive_events/module_detail.html
apps/mapideas/templates/a4_candy_mapideas/includes/mapidea_list_item.html
apps/mapideas/templates/a4_candy_mapideas/mapidea_detail.html
apps/organisations/templates/a4_candy_organisations/communication_form_social_media.html
apps/topicprio/templates/a4_candy_topicprio/includes/topic_list_item.html
apps/topicprio/templates/a4_candy_topicprio/topic_detail.html

[2364] badge size and colorising fix

---

apps/userdashboard/views.py

This should fix https://sentry.liqd.net/organizations/liqd/issues/3179/

userdashboard/views: exclude paragraphs from comment actions

---

adhocracy-plus/templates/account/email/account_already_exists.en.email
apps/contrib/management/commands/send_test_emails.py
apps/users/forms.py

apps/users: adding "account already exists" email

---

locale-source/locale/de/LC_MESSAGES/django.po
locale-source/locale/de/LC_MESSAGES/djangojs.po
locale-source/locale/en/LC_MESSAGES/django.po
locale-source/locale/en/LC_MESSAGES/djangojs.po
locale-source/locale/hu/LC_MESSAGES/django.po
locale-source/locale/hu/LC_MESSAGES/djangojs.po
locale-source/locale/ky/LC_MESSAGES/django.po
locale-source/locale/ky/LC_MESSAGES/djangojs.po
locale-source/locale/nl/LC_MESSAGES/django.po
locale-source/locale/nl/LC_MESSAGES/djangojs.po
locale-source/locale/ru/LC_MESSAGES/django.po
locale-source/locale/ru/LC_MESSAGES/djangojs.po
locale-source/locale/tr/LC_MESSAGES/django.po
locale-source/locale/tr/LC_MESSAGES/djangojs.po

locale: makemessages

---

apps/userdashboard/templates/a4_candy_userdashboard/userdashboard_overview.html
apps/userdashboard/views.py
tests/userdashboard/views/test_userdashboard_activities_view.py
tests/userdashboard/views/test_userdashboard_overview_view.py

Should we merge this into release and test on stage?

hotfix to be removed after proper fix: delete actions from userdashboard

---

apps/userdashboard/views.py
package.json
requirements/base.txt

depends on https://github.com/liqd/adhocracy4/pull/1421

Jd 2023 06 userdashboard filter 2

---

apps/notifications/templates/a4_candy_notifications/emails/notify_followers_event_upcomming.en.email
changelog/7427.md
locale-source/locale/de/LC_MESSAGES/django.po
locale-source/locale/de/LC_MESSAGES/djangojs.po
locale-source/locale/en/LC_MESSAGES/django.po
locale-source/locale/en/LC_MESSAGES/djangojs.po
locale-source/locale/hu/LC_MESSAGES/django.po
locale-source/locale/hu/LC_MESSAGES/djangojs.po
locale-source/locale/ky/LC_MESSAGES/django.po
locale-source/locale/ky/LC_MESSAGES/djangojs.po
locale-source/locale/nl/LC_MESSAGES/django.po
locale-source/locale/nl/LC_MESSAGES/djangojs.po
locale-source/locale/ru/LC_MESSAGES/django.po
locale-source/locale/ru/LC_MESSAGES/djangojs.po
locale-source/locale/tr/LC_MESSAGES/django.po
locale-source/locale/tr/LC_MESSAGES/djangojs.po
tests/notifications/test_follower_notifications.py

- changes email template for notifying followers of upcoming event
- see https://taiga.liqd.net/project/liqd-liquid-software/us/7427

[7427] notifications/templates: wording change event invitation mail

---

tests/projects/conftest.py
tests/projects/test_project_module_detail_view.py

test that the back button in the module detail view gets passed the correct initial slide parameter

[7428] tests: add test for multi-module timeline module detail back button

---

adhocracy-plus/assets/scss/_form.scss
apps/documents/assets/ParagraphForm.jsx
apps/organisations/templates/a4_candy_organisations/organisation_data_protection.html
apps/organisations/templates/a4_candy_organisations/organisation_imprint.html
apps/organisations/templates/a4_candy_organisations/organisation_information.html
apps/organisations/templates/a4_candy_organisations/organisation_netiquette.html
apps/organisations/templates/a4_candy_organisations/organisation_terms_of_use.html
requirements/base.txt

[7632] refactor documents to work with new ckeditor5

---

adhocracy-plus/config/settings/base.py
apps/account/views.py
apps/users/__init__.py
apps/users/utils.py
changelog/0003.md

remove kyrgyz translation for ckeditor

---

adhocracy-plus/config/settings/base.py
apps/users/__init__.py
apps/users/middleware.py
changelog/2658.md
tests/users/test_views.py

[2568] Add custom language middleware

---

adhocracy-plus/assets/scss/components/_header_lower.scss
adhocracy-plus/assets/scss/components/_tabs.scss

fixes https://github.com/liqd/adhocracy-plus/issues/2597

scss/components: fix .tablist and organization logo z-index

---

adhocracy-plus/templates/account/signup.html
apps/users/forms.py
changelog/8103.md

to be merged after #2601 
**Tasks**

[8103] signup and captcha improvements

---

.gitignore
changelog/0004.md
docs/api.md
docs/howtomkdocs.md
docs/index.md
docs/reference.md
mkdocs.yml
requirements/dev.txt

mkdocs: initial html documentation

---

apps/contrib/templates/a4_candy_contrib/component_library.html
apps/contrib/widgets.py
apps/ideas/views.py
changelog/8152.md

[8152] Add anchor for ordering

---

apps/documents/templatetags/react_documents.py

submit work again.
fixes #2590
**Tasks**

apps/documents: fix typo in document template tag to make the reload on

---

apps/documents/templates/a4_candy_documents/chapter_detail.html
changelog/_2618.md

fixes https://github.com/liqd/adhocracy-plus/issues/2585

fix #2585 a4_candy_documents/chapter_detail: expand toc on all chapters

---

adhocracy-plus/assets/scss/_utility.scss
apps/userdashboard/templates/a4_candy_userdashboard/base_userdashboard.html
apps/users/templates/a4_candy_users/user_detail.html
changelog/2599.md

fixes https://github.com/liqd/adhocracy-plus/issues/2599

templates/base_userdashboard: fix text overlap

---

apps/users/adapters.py
changelog/2696.md

[2696] Fix unknown account email not rendering 

---

changelog/_1111.md
requirements/dev.txt

requirements/dev.py: add pytest-mock

---

requirements/base.txt

deps: update autoslug to upstream

---

CHANGELOG.md
changelog/_1111.md
package.json
requirements/base.txt

release v2406.3

---

apps/account/templates/a4_candy_account/emails/account_deleted.en.email
changelog/2720.md
changelog/2721.md
locale-source/locale/de/LC_MESSAGES/django.po
locale-source/locale/en/LC_MESSAGES/django.po
locale-source/locale/hu/LC_MESSAGES/django.po
locale-source/locale/ky/LC_MESSAGES/django.po
locale-source/locale/nl/LC_MESSAGES/django.po
locale-source/locale/ru/LC_MESSAGES/django.po
locale-source/locale/tr/LC_MESSAGES/django.po

Jd 2024 06 fix email translation

---

adhocracy-plus/config/urls.py
apps/users/middleware.py
apps/users/views.py
changelog/2719.md

the users preferred language.
- add missing cookie settings to language cookie
fixes #2719
**Tasks**

apps/users: make switching the language via the indicator also change

---

locale-source/locale/de/LC_MESSAGES/django.po
locale-source/locale/de/LC_MESSAGES/djangojs.po
locale-source/locale/en/LC_MESSAGES/django.po
locale-source/locale/en/LC_MESSAGES/djangojs.po
locale-source/locale/hu/LC_MESSAGES/django.po
locale-source/locale/hu/LC_MESSAGES/djangojs.po
locale-source/locale/ky/LC_MESSAGES/django.po
locale-source/locale/ky/LC_MESSAGES/djangojs.po
locale-source/locale/nl/LC_MESSAGES/django.po
locale-source/locale/nl/LC_MESSAGES/djangojs.po
locale-source/locale/ru/LC_MESSAGES/django.po
locale-source/locale/ru/LC_MESSAGES/djangojs.po
locale-source/locale/tr/LC_MESSAGES/django.po
locale-source/locale/tr/LC_MESSAGES/djangojs.po

pull translations from transifex

---

CHANGELOG.md
changelog/2719.md
changelog/2720.md
changelog/2721.md
package.json
requirements/base.txt

release v2406.4

---

apps/debate/views.py
apps/offlineevents/views.py
apps/topicprio/views.py
changelog/1111.md
changelog/2222.md
docs/deletion.md
tests/account/test_views.py
tests/budgeting/test_image_upload_and_deletion.py
tests/interactiveevents/test_image_upload_and_deletion.py
tests/organisations/test_image_upload_and_deletion.py
tests/projects/test_image_upload_and_deletion.py

[7619] image deletion docs

---

changelog/3333.md
docs/img_saving_and_deletion.md
mkdocs.yml

mkdocs: add image docs

---

adhocracy-plus/config/settings/base.py
adhocracy-plus/config/urls.py
apps/projects/serializers.py
changelog/8305.md
docs/authentication.md
mkdocs.yml
requirements/base.txt
tests/account/test_api.py
tests/projects/test_app_project_api.py

[8305] added jwt for projects api 

---

adhocracy-plus/config/settings/polygons.py

[8357] config/settings: add src for polygon

---

apps/projects/serializers.py
changelog/2771.md
tests/projects/test_app_project_api.py

apps/projects: add project url to app project serializer

---

.github/workflows/django.yml

github/workflows: bump versions to ubuntu 24.04

---

changelog/8400.md
locale-source/locale/de/LC_MESSAGES/django.po
locale-source/locale/de/LC_MESSAGES/djangojs.po
locale-source/locale/en/LC_MESSAGES/django.po
locale-source/locale/en/LC_MESSAGES/djangojs.po
locale-source/locale/hu/LC_MESSAGES/django.po
locale-source/locale/hu/LC_MESSAGES/djangojs.po
locale-source/locale/ky/LC_MESSAGES/django.po
locale-source/locale/ky/LC_MESSAGES/djangojs.po
locale-source/locale/nl/LC_MESSAGES/django.po
locale-source/locale/nl/LC_MESSAGES/djangojs.po
locale-source/locale/ru/LC_MESSAGES/django.po
locale-source/locale/ru/LC_MESSAGES/djangojs.po
locale-source/locale/tr/LC_MESSAGES/django.po
locale-source/locale/tr/LC_MESSAGES/djangojs.po

8400 translations: pulled from transifex

---

changelog/8477.md
docs/open_poll.md
mkdocs.yml

docs open poll

---

package.json
requirements/base.txt

to bring in the changes from a4 for the poll
**Tasks**

update a4 hash

---

adhocracy-plus/assets/scss/components/_a4-editpoll.scss
adhocracy-plus/assets/scss/style.scss

styles for https://github.com/liqd/adhocracy4/pull/1726

a4-polls: fix unregistered users checkbox

---

Makefile
apps/budgeting/templates/a4_candy_budgeting/includes/proposal_list_item.html
apps/contrib/templates/a4_candy_contrib/component_library.html
apps/ideas/templates/a4_candy_ideas/includes/idea_list_item.html
apps/interactiveevents/assets/Filters.jsx
apps/interactiveevents/assets/QuestionModerator.jsx
apps/interactiveevents/assets/QuestionUser.jsx
apps/mapideas/templates/a4_candy_mapideas/includes/mapidea_list_item.html
apps/topicprio/templates/a4_candy_topicprio/includes/topic_list_item.html
changelog/8382.md

**Tasks**
fixes #2872
analogous to https://github.com/liqd/a4-meinberlin/commit/95f71b874212218d0a899ecb0ab83f2d2053a834

replace chevron rating icons with new thumb icon

---

CHANGELOG.md

release v2501.2

---

CHANGELOG.md
changelog/_0001.md
package.json
requirements/base.txt

release v2501.3

---

CHANGELOG.md
changelog/8593.md

release v2501.4

---

adhocracy-plus/assets/scss/components/_a4-comments.scss
adhocracy-plus/assets/scss/components/_a4-modal.scss
adhocracy-plus/assets/scss/style.scss
apps/contrib/templates/a4_candy_contrib/item_detail.html

dependency of https://github.com/liqd/adhocracy4/pull/1758

a4-modals: adapt styles to changes in a4

---

adhocracy-plus/templates/socialaccount/signup.html

STS-232
Adds to #2951, merging since deving on the server

templates: add captcha to socialaccount

---

adhocracy-plus/templates/socialaccount/signup.html

STS-232
Adds to https://github.com/liqd/adhocracy-plus/pull/2951 #2953 - merging since deving on the server

templates: add form.media for captcha js

---

adhocracy-plus/config/settings/base.py
adhocracy-plus/templates/a4polls/includes/unregistered-users-info-box.html
adhocracy-plus/templates/footer.html
apps/users/templates/a4_candy_users/indicator.html
changelog/419.md

[#419] templates: Update manual link text to 'Help Center', make links consistent

---

README.md
changelog/250520.md

**Tasks**
- [-] PR name contains story or task reference
- [x ] Documentation (docs and inline)
- [-] Tests (including n+1 and django_assert_num_queries where applicable)
- [x ] Changelog

docs: Update README.md, include libmagic install step

---

Makefile
README.md
changelog/0001.md

update postgresql setup

---

docs/geolocation.md

add old geolocation format in the docs

---

docs/postgresql.md

docs:  Change Postgres related Docs
